hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "x11")
hl.env("ILLOGICAL_IMPULSE_VIRTUAL_ENV", "~/.local/state/quickshell/.venv")

-- Load system configurations if generated by config-loader
local home = os.getenv("HOME")
if home then
    if is_file_exists(home .. "/.config/hypr/gpu.lua") then
        require("gpu")
    end
    -- Load cursor settings directly from cursor.lua
    if is_file_exists(home .. "/.config/hypr/cursor.lua") then
        dofile(home .. "/.config/hypr/cursor.lua")
    end
end


-- Tablet configurations for osu!
hl.config({
    device = {
        {
            name = "virtual_tablet",
            active_area_size = "1000 1000",
            active_area_position = "0 1024"
        },
        {
            name = "virtual_tablet_1",
            active_area_size = "1000 1000",
            active_area_position = "0 1024"
        }
    }
})
