# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

bindd = Ctrl Alt, F, Fit to screen, exec,bash $archSetupScripts/keybinds/zoom_to_fit.sh
bindd = Alt, Q, Mixer, exec,bash $archSetupScripts/keybinds/mixer.sh
bindd = Ctrl+Alt, Slash, Toggle Workspace Modifier (Alt/Super), exec, ~/dots-arch-hyprland/scripts/hypr/keybinds/toggle_workspace_mod.sh
bindd = Ctrl Alt, period, Toggle Hover to Focus, exec, ~/dots-arch-hyprland/scripts/hypr/keybinds/toggle_hover_to_focus.sh