def get_install_items(repo_dir):
    """Returns a list of dictionaries representing the installation items."""
    return [
        {"type": "header", "text": "--- Core ---"},
        {
            "type": "essential",
            "text": "Install paru (AUR Helper)",
            "func": "install_paru",
            "group": "Package Managers",
            "description": "Installs paru, an AUR helper that simplifies installing and managing packages from the Arch User Repository.",
        },
        {
            "type": "essential",
            "text": "Install rate-mirrors and Rank Mirrors",
            "func": "install_rate_mirrors_and_rank",
            "group": "System Optimization",
            "description": "Installs rate-mirrors and then runs the script to rank Arch Linux mirrors for optimal performance.",
        },
        {
            "type": "essential",
            "text": "Install Chaotic AUR",
            "func": f"bash {repo_dir}/cli/install_chaotic_aur.sh",
            "group": "Package Managers",
            "description": "Installs the Chaotic-AUR repository, providing a large collection of pre-built AUR packages.",
        },
        {
            "type": "essential",
            "text": "Set up Git Credential Management",
            "func": "setup_git_credential_management",
            "group": "Git Credentials",
            "description": "Sets up Git Credential Manager to securely store and manage Git credentials.",
        },
        {
            "type": "essential",
            "text": "Install Fish Shell",
            "func": "install_fish",
            "group": "Shell (Fish)",
            "description": "Installs the Fish shell, a smart and user-friendly command line shell.",
        },
        {
            "type": "essential",
            "text": "Install end-4's Hyprland Dots",
            "func": "install_end4_hyprland_dots",
            "group": "Hyprland Core",
            "description": "Installs the core Hyprland configuration files and dependencies from end-4.",
        },
        {
            "type": "essential",
            "text": "Load all configurations (GPU, cursor, etc)",
            "func": f"bash {repo_dir}/cli/load_configs.sh",
            "group": "Hyprland Configuration",
            "description": "Loads and applies various system configurations, including GPU settings, cursor themes, and other dotfiles.",
        },
        {
            "type": "essential",
            "text": "Install and Run nwg-displays",
            "func": "install_nwg_displays",
            "group": "Hyprland Utilities",
            "description": "Installs and runs nwg-displays, a small utility for managing displays in Wayland compositors like Hyprland.",
        },
        {
            "type": "essential",
            "text": "Install hyprshutdown",
            "func": "install_hyprshutdown",
            "group": "Hyprland Utilities",
            "description": "Installs hyprshutdown, a utility to gracefully shut down Hyprland.",
        },
        {
            "type": "essential",
            "text": "Install Vicinae",
            "func": "install_vicinae",
            "group": "Application Launcher",
            "description": "Installs Vicinae, application launcher.",
        },
        {
            "type": "essential",
            "text": "Adjust GRUB menu resolution",
            "func": "adjust_grub_menu",
            "group": "Bootloader (GRUB)",
            "description": "Adjusts the resolution of the GRUB boot menu for better display compatibility.",
        },
        {
            "type": "essential",
            "text": "Enable os-prober for GRUB",
            "func": "enable_os_prober",
            "group": "Bootloader (GRUB)",
            "description": "Enables os-prober in GRUB to detect and list other operating systems installed on the machine.",
        },
        {
            "type": "essential",
            "text": "Install Linux Headers",
            "func": "install_linux_headers",
            "group": "System Kernel",
            "description": "Installs essential Linux kernel headers for building modules and other system components.",
        },
        {
            "type": "optional",
            "text": "Install NVIDIA Drivers (Proprietary)",
            "func": "install_nvidia_drivers",
            "group": "Graphics",
            "description": "Installs NVIDIA drivers and utilities for better graphics performance.",
        },
        {
            "type": "essential",
            "text": "Install systemd-oomd.service",
            "func": "install_systemd_oomd",
            "group": "System Services",
            "description": "Installs and enables systemd-oomd, a userspace OOM killer that can prevent system freezes under heavy memory pressure.",
        },
        {
            "type": "essential",
            "text": "Install ananicy-cpp",
            "func": "install_ananicy_cpp",
            "group": "System Optimization",
            "description": "Installs ananicy-cpp, a C++ port of ananicy, which automatically adjusts process nice values and I/O priorities for better system responsiveness.",
        },
        {
            "type": "essential",
            "text": "Install Mission Center",
            "func": "install_mission_center",
            "group": "System Monitoring",
            "description": "Installs Mission Center, a modern and fast system monitor for Linux.",
        },
        {
            "type": "essential",
            "text": "Install jq",
            "func": "install_jq",
            "group": "CLI Utilities",
            "description": "Installs jq, a lightweight and flexible command-line JSON processor.",
        },
        {
            "type": "essential",
            "text": "Install xorg-xhost and set root access",
            "func": "install_xorg_xhost_and_xhost_rule",
            "group": "Hyprland Core",
            "description": "Installs xorg-xhost for X server access control and sets a rule to allow root to connect to the X server.",
        },
        {"type": "header", "text": "--- Package Management ---"},
        {
            "type": "essential",
            "text": "Install Flatpak",
            "group": "Package Managers",
            "func": "install_flatpak",
            "description": "Installs Flatpak, a universal packaging system for Linux applications, providing sandboxed environments.",
        },
        {
            "type": "essential",
            "text": "Install downgrade utility",
            "func": "install_downgrade",
            "group": "Package Managers",
            "description": "Installs downgrade, a utility to downgrade one or more packages to a version in your cache or from the Arch Linux Archive.",
        },
        {
            "type": "optional",
            "text": "Install npm",
            "func": "install_npm",
            "group": "Development Runtimes",
            "description": "Installs npm (Node Package Manager), a package manager for JavaScript.",
        },
        {
            "type": "optional",
            "text": "Install pnpm",
            "func": "install_pnpm",
            "group": "Development Runtimes",
            "description": "Installs pnpm, a fast, disk-space efficient package manager for Node.js.",
        },
        {"type": "header", "text": "--- System ---"},
        {
            "type": "essential",
            "text": "Install inotify-tools",
            "func": "install_inotify_tools",
            "group": "System Monitoring",
            "description": "Installs inotify-tools, a set of command-line programs for monitoring filesystem events.",
        },
        {
            "type": "essential",
            "text": "Install Power Options (TLP)",
            "func": "install_power_options",
            "group": "Power Management",
            "description": "Installs TLP, an advanced power management tool for Linux, optimized for laptops to save battery power.",
        },
        {
            "type": "essential",
            "text": "Install FUSE",
            "func": "install_fuse",
            "group": "System Libraries",
            "description": "Installs FUSE (Filesystem in Userspace), allowing non-privileged users to create their own file systems.",
        },
        {
            "type": "essential",
            "text": "Install NTFS Support (fast ntfs3 & utilities)",
            "func": "install_ntfs_3g",
            "group": "System Libraries",
            "description": "Provides support for NTFS partitions using the fast kernel-level 'ntfs3' driver, and installs 'ntfs-3g' for essential maintenance utilities (like ntfsfix).",
        },
        {"type": "header", "text": "--- Desktop & Theming ---"},
        {
            "type": "essential",
            "text": "Install nwg-look",
            "func": "install_nwg_look",
            "group": "Hyprland Utilities",
            "description": "Installs nwg-look, a GTK settings editor for Wayland.",
        },
        {
            "type": "essential",
            "text": "Install qt5ct",
            "func": "install_qt5ct",
            "group": "Qt Theming",
            "description": "Installs qt5ct, a tool to configure Qt5 application appearance.",
        },
        {
            "type": "essential",
            "text": "Install qt6ct",
            "func": "install_qt6ct",
            "group": "Qt Theming",
            "description": "Installs qt6ct, a tool to configure Qt6 application appearance.",
        },
        {
            "type": "essential",
            "text": "Install SDDM Astronaut Theme",
            "func": "install_sddm_theme",
            "group": "Login Manager (SDDM)",
            "description": "Installs the Astronaut theme for SDDM, the Simple Desktop Display Manager.",
        },
        {
            "type": "essential",
            "text": "Install Catppuccin Theme for GRUB",
            "func": "select_and_install_catppuccin_grub_theme",
            "group": "Bootloader (GRUB)",
            "description": "Installs the Catppuccin theme for GRUB, enhancing the bootloader's appearance.",
        },
        {
            "type": "essential",
            "text": "Install Catppuccin Fish Theme",
            "func": "install_catppuccin_fish_theme",
            "group": "Shell (Fish)",
            "description": "Installs the Catppuccin theme for the Fish shell, providing a visually pleasing command-line experience.",
        },
        {"type": "header", "text": "--- Applications ---"},
        {
            "type": "essential",
            "text": "Install Rofi",
            "func": "install_rofi",
            "group": "Application Launcher",
            "description": "Installs Rofi, a window switcher, application launcher, and dmenu replacement.",
        },
        {
            "type": "essential",
            "text": "Install Ulauncher Catppuccin Theme",
            "func": "install_ulauncher_catppuccin_theme",
            "group": "Application Launcher",
            "description": "Installs the Catppuccin theme for Ulauncher.",
        },
        {
            "type": "essential",
            "text": "Install VS Code Insiders",
            "func": "install_vscode_insiders",
            "group": "Development Tools",
            "description": "Installs VS Code Insiders, the daily updated version of Visual Studio Code with the latest features.",
        },
        {
            "type": "essential",
            "text": "Fix VSCode Insiders permissions",
            "func": "fix_vscode_permissions",
            "group": "Development Tools",
            "description": "Fixes permissions for VS Code Insiders to ensure proper functionality.",
        },
        {
            "type": "essential",
            "text": "Install Discord",
            "func": "install_discord",
            "group": "Communication",
            "description": "Installs the official Discord client.",
        },
        {
            "type": "optional",
            "text": "Install Vencord (Discord Mod)",
            "func": "install_vencord",
            "group": "Communication",
            "description": "Installs the Vencord mod for Discord.",
        },
        {
            "type": "essential",
            "text": "Install Steam",
            "func": "install_steam",
            "group": "Gaming",
            "description": "Installs Steam, the popular digital distribution platform for video games.",
        },
        {
            "type": "essential",
            "text": "Install Pinta",
            "func": "install_pinta",
            "group": "Graphics & Media",
            "description": "Installs Pinta, a free, open-source drawing/editing program.",
        },
        {
            "type": "essential",
            "text": "Install Nomacs",
            "func": "install_nomacs",
            "group": "Graphics & Media",
            "description": "Installs Nomacs, a fast and easy-to-use image viewer.",
        },
        {
            "type": "optional",
            "text": "Install YouTube Music (Pear)",
            "func": "install_youtube_music_pear",
            "group": "Graphics & Media",
            "description": "Installs YouTube Music (Pear Desktop).",
        },
        {
            "type": "optional",
            "text": "Install HandBrake",
            "func": "install_handbrake",
            "group": "Graphics & Media",
            "description": "Installs HandBrake, a free and open-source video transcoder.",
        },
        {
            "type": "optional",
            "text": "Install EasyEffects",
            "func": "install_easyeffects",
            "group": "Audio",
            "description": "Installs EasyEffects, a PulseAudio/PipeWire application for applying audio effects.",
        },
        {
            "type": "essential",
            "text": "Install Pavucontrol-Qt",
            "func": "install_pavucontrol",
            "group": "Audio",
            "description": "Installs Pavucontrol, a simple GTK based volume control tool for PulseAudio.",
        },
        {
            "type": "optional",
            "text": "Install Microsoft Edge (Stable)",
            "func": "install_ms_edge_stable",
            "group": "Web Browsers",
            "description": "Installs the Microsoft Edge (Stable) browser.",
        },
        {
            "type": "essential",
            "text": "Install Zen Browser",
            "func": "install_zen_browser",
            "group": "Web Browsers",
            "description": "Installs Zen Browser, a privacy-focused web browser.",
        },
        {
            "type": "essential",
            "text": "Install Switcheroo",
            "func": "install_switcheroo",
            "group": "General Utilities",
            "description": "Installs Switcheroo, a simple application switcher for Wayland.",
        },
        {
            "type": "essential",
            "text": "Install BleachBit",
            "func": "install_bleachbit",
            "group": "System Cleanup",
            "description": "Installs BleachBit, a system cleaner to free up disk space and maintain privacy.",
        },
        {
            "type": "essential",
            "text": "Install QDirStat",
            "func": "install_qdirstat",
            "group": "Disk Usage",
            "description": "Installs QDirStat, a graphical disk usage display.",
        },
        {
            "type": "optional",
            "text": "Install GParted (Partition Editor)",
            "func": "install_gparted",
            "group": "System Utilities",
            "description": "Installs GParted, a graphical partition editor for creating, reorganizing, and deleting disk partitions.",
        },
        {
            "type": "essential",
            "text": "Install Flatseal",
            "func": "install_flatseal",
            "group": "Flatpak Management",
            "description": "Installs Flatseal, a graphical utility to review and modify permissions for your Flatpak applications.",
        },
        {
            "type": "optional",
            "text": "Install gdrive-bisync (Google Drive)",
            "func": "install_gdrive_bisync",
            "group": "Cloud Storage",
            "description": "Installs gdrive-bisync, a Google Drive client for Linux.",
        },
        {
            "type": "optional",
            "text": "Install Waydroid",
            "func": "install_waydroid",
            "group": "Android Emulation",
            "description": "Installs Waydroid, a container-based approach to boot a full Android system on a Linux device.",
        },
        {
            "type": "optional",
            "text": "Install Waydroid Helper",
            "func": "install_waydroid_helper",
            "group": "Android Emulation",
            "description": "Installs Waydroid Helper, a utility to simplify Waydroid management.",
        },
        {
            "type": "optional",
            "text": "Install Waydroid Extra Script",
            "func": "install_waydroid_extra_script",
            "group": "Android Emulation",
            "description": "Installs the Waydroid Extra Script for enhanced Waydroid management.",
        },
        {
            "type": "optional",
            "text": "Install Virtualization (libvirt, virt-manager, QEMU)",
            "func": "install_virt_packages",
            "group": "Virtualization",
            "description": "Installs essential virtualization tools including libvirt, virt-manager, QEMU, dnsmasq, and dmidecode, and enables the libvirtd service.",
        },
        {
            "type": "optional",
            "text": "Install Fisher",
            "func": "install_fisher",
            "group": "CLI Utilities",
            "description": "Installs Fisher, a plugin manager for the Fish shell.",
        },
        {
            "type": "optional",
            "text": "Install gcalcli",
            "func": "install_gcalcli",
            "group": "CLI Utilities",
            "description": "Installs gcalcli, a command-line tool for Google Calendar.",
        },
        {"type": "header", "text": "--- Hardware & Peripherals ---"},
        {
            "type": "optional",
            "text": "Install v4l2loopback (for Droidcam/OBS)",
            "func": "install_v4l2loopback",
            "group": "Drivers & Modules",
            "description": "Installs v4l2loopback, a kernel module that creates virtual video devices, useful for Droidcam or OBS.",
        },
        {
            "type": "optional",
            "text": "Install Droidcam",
            "func": "install_droidcam",
            "group": "Webcam",
            "description": "Installs Droidcam, allowing you to use your Android phone as a webcam.",
        },
        {
            "type": "optional",
            "text": "Install MX002 Tablet Driver",
            "func": "install_mx002_driver",
            "group": "Drivers & Modules",
            "description": "Installs the necessary drivers for MX002 series drawing tablets.",
        },
        {
            "type": "optional",
            "text": "Install Linux Wallpaper Engine",
            "func": "install_wallpaper_engine",
            "group": "Wallpaper Engine",
            "description": "Installs Linux Wallpaper Engine, a port of the popular Wallpaper Engine for Linux.",
        },
        {
            "type": "optional",
            "text": "Install Linux Wallpaper Engine GUI",
            "func": "install_wallpaper_engine_gui",
            "group": "Wallpaper Engine",
            "description": "Installs the GUI for Linux Wallpaper Engine using paru.",
        },
    ]
